services:
  mysql:
    image: 'mysql:8.1'
    volumes:
      - './mysql:/var/lib/mysql'
    environment:
      MYSQL_DATABASE: cloud
      MYSQL_USER: cloud
      MYSQL_PASSWORD: cloud@dmin
      MYSQL_ROOT_PASSWORD: rootroot
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
  redis:
    image: 'redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
